server:
  port: 8080
spring:
  application:
    name: Scheduledemo
  datasource:
    initialization-mode: always
    data:
      - classpath:db/migrations/V1__quartz_table.sql
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:quartz_scheduler}
    username: ${DB_USERNAME:postgres}
    validationQuery: SELECT 1
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
